create table if not exists public.score_history (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),

    timestamp_utc timestamptz,
    supporting_gold_pct numeric,
    opposing_gold_pct numeric,
    bias text,
    confidence text,
    edge_pts numeric,

    spot_xauusd_latest numeric,
    spot_xauusd_change_pct numeric,
    gold_futures_latest numeric,
    gold_futures_change_pct numeric,

    dxy_latest numeric,
    dxy_change_pct numeric,
    us10y_latest numeric,
    us10y_change_bps numeric,
    real_yield_latest numeric,
    real_yield_change_bps numeric,
    spx_change_pct numeric,
    vix_change_pct numeric,

    dxy_state text,
    us10y_state text,
    real_yields_state text,
    fed_tone_state text,
    fed_tone_label text,
    fed_tone_confidence numeric,
    geopolitics_state text,
    risk_sentiment_state text,
    gold_news_state text,
    gold_news_articles numeric,

    notes text,
    price_1h_later numeric,
    price_4h_later numeric,
    bias_result_1h text,
    bias_result_4h text
);
